services:
  python_router:

    build: ./python_router
    ports:
      - "8880:9000"
    develop:
      watch:
        - action: sync
          path: ./python_router
          target: /app
    depends_on:
      - backend_good
      - backend_average
      - backend_faulty

  go_router:
    build: ./go_router
    ports:
      - "8881:9000"
    develop:
      watch:
        - action: sync
          path: ./go_router
          target: /app
    depends_on:
      - backend_good
      - backend_faulty
      - backend_average

  backend_good:
    build: ./backends
    environment:
      - BACKEND_NAME="backend_good-0.1"
      - FAILURE_RATE=0.0
      - LOAD_PER_REQUEST_S=0
      - DOWNTIME_RATE=0
    ports:
      - "9001:9000"

  backend_average:
    build: ./backends
    environment:
      - BACKEND_NAME="backend_average-0.1"
      - FAILURE_RATE=0.3
      - LOAD_PER_REQUEST_S=1
      - DOWNTIME_RATE=0.3
    ports:
      - "9002:9000"

  backend_faulty:
    build: ./backends
    environment:
      - BACKEND_NAME="backend_faulty-0.9"
      - FAILURE_RATE=0.9
      - LOAD_PER_REQUEST_S=1
      - DOWNTIME_RATE=0
    ports:
      - "9003:9000"
